apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.mongo.pv }}
spec:
  capacity:
    storage: 1Gi
  
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: {{ .Values.mongo.storageClassName }}
  gcePersistentDisk: 
    pdName: my-data-disk
    fsType: ext4 
  
  
