apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.mongo.pvc }}
  
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 800Mi
  storageClassName: slow
  
