apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mongo.serviceName }}
  labels:
    run: {{ template "fullname" . }}-mongo
spec:
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    run: {{ template "fullname" . }}-mongo

