nodeapp:
  repository: learnk8s/knote-js:1.0.0
#  tag: "1.0.0"
#  replicaCount: 1
  pullPolicy: IfNotPresent

service:
  nodeapp:
    name: nodeapp-service
    type: LoadBalancer
    protocol: TCP
    externalPort: 80
    internalPort: 3000  
