apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.nodeapp.name }}
spec:
  type: {{ .Values.service.nodeapp.type }}
  ports:
    - port: {{ .Values.service.nodeapp.externalPort }}
      targetPort: {{ .Values.service.nodeapp.internalPort }} 
  selector:
    run: {{ template "fullname" . }}-nodejs
